[[plugins]]
repo = 'Shougo/dein.vim'

# git差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# coc
[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
hool_add = '''
source ~/.config/nvim/plugins/coc.rc.vim
'''

# nvimインターフェース統合
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''

# ファイルエクスプローラー
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git']
hook_add = '''
source ~/.config/nvim/plugins/defx.rc.vim
'''

# defxgitアイコン
[[plugins]]
repo = 'kristijanhusak/defx-git'
hook_add = '''
source ~/.config/nvim/plugins/defx-git.rc.vim
'''

# HTMLタグ操作
[[plugins]]
repo = 'rstacruz/sparkup'

# 囲い
[[plugins]]
repo = 'tpope/vim-surround'

# 簡単コメント
[[plugins]]
repo = 'tpope/vim-commentary'

# Airlineカスタマイズ
[[plugins]]
repo = 'vim-airline/vim-airline'

# Airlineテーマ
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# インクリメンタルサーチ
[[plugins]]
repo = 'junegunn/fzf.vim'
build = './install --all'
merged = 0

# 置換プレビュー
[[plugins]]
repo = 'markonm/traces.vim'

# SATySFi
[[plugins]]
repo = 'qnighy/satysfi.vim'

# Rust
[[plugins]]
repo = 'rust-lang/rust.vim'

# インデントをきれいに
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_color_term = 239
let g:indentLine_color_gui = '#708090'
let g:indentLine_char = '|'
'''

# 虹
[[plugins]]
repo = 'junegunn/rainbow_parentheses.vim'

# tagBar
[[plugins]]
repo = 'majutsushi/tagbar'

# gruvbox colorscheme
[[plugins]]
repo = 'morhetz/gruvbox'

# javascript
[[plugins]]
repo = 'pangloss/vim-javascript'

# js syntax highlight
[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'othree/es.next.syntax.vim'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]]
repo = 'ternjs/tern_for_vim'
